name: Lint Check with ReviewDog

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-check:
    name: Lint Check
    runs-on: self-hosted
    steps:
      - name: ðŸ“¦ Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: ðŸ“¦ Install Reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@v1


      - uses: yu-iskw/action-sqlfluff@v2
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "0.9.0"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: '${{ github.workspace }}/migrations/*'